"""add user token_version

Revision ID: 3ba10fe09836
Revises: 3c190bb8324f
Create Date: 2026-07-12 09:57:12.001010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ba10fe09836'
down_revision: Union[str, None] = '3c190bb8324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
