"""add warehouse and stock management

Revision ID: 3c190bb8324f
Revises: a998281f1c54
Create Date: 2026-07-12 09:05:04.215053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c190bb8324f'
down_revision: Union[str, None] = 'a998281f1c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_organization_id'), 'warehouses', ['organization_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('cable', 'transceiver', 'rail_kit', 'screw_kit', 'spare_psu', 'spare_drive', 'other', name='stock_category'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_threshold', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('pcs', 'box', 'meter', 'roll', name='stock_unit'), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_organization_id'), 'stock_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_items_sku'), 'stock_items', ['sku'], unique=False)
    op.create_index(op.f('ix_stock_items_warehouse_id'), 'stock_items', ['warehouse_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('received', 'issued', 'adjusted', 'returned', name='movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('resulting_quantity', sa.Integer(), nullable=False),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_email', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('linked_device_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_organization_id'), 'stock_movements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_stock_item_id'), 'stock_movements', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_timestamp'), 'stock_movements', ['timestamp'], unique=False)
    op.add_column('devices', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devices_warehouse_id'), 'devices', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_warehouse_id'), table_name='devices')
    op.drop_column('devices', 'warehouse_id')
    op.drop_index(op.f('ix_stock_movements_timestamp'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_stock_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_organization_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_items_warehouse_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_sku'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_organization_id'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_warehouses_organization_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
