"""add device photo_url

Revision ID: 8e658331fc0c
Revises: d92cb7a92fb6
Create Date: 2026-07-11 21:47:54.794398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e658331fc0c'
down_revision: Union[str, None] = 'd92cb7a92fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'photo_url')
    # ### end Alembic commands ###
