"""add power fields

Revision ID: a998281f1c54
Revises: 313150f0c34a
Create Date: 2026-07-12 00:41:35.660781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a998281f1c54'
down_revision: Union[str, None] = '313150f0c34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('power_watts', sa.Integer(), nullable=True))
    # backfill existing racks with the default 10kW capacity
    op.add_column('racks', sa.Column('power_capacity_watts', sa.Integer(), nullable=True, server_default='10000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racks', 'power_capacity_watts')
    op.drop_column('devices', 'power_watts')
    # ### end Alembic commands ###
