"""add rack floorplan position and room dimensions

Revision ID: cbda8662f5fe
Revises: 8e658331fc0c
Create Date: 2026-07-11 21:57:08.968117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbda8662f5fe'
down_revision: Union[str, None] = '8e658331fc0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; the app supplies its own defaults on insert
    op.add_column('racks', sa.Column('pos_x', sa.Float(), nullable=False, server_default='0'))
    op.add_column('racks', sa.Column('pos_y', sa.Float(), nullable=False, server_default='0'))
    op.add_column('racks', sa.Column('width_units', sa.Float(), nullable=False, server_default='1'))
    op.add_column('racks', sa.Column('depth_units', sa.Float(), nullable=False, server_default='1'))
    op.add_column('rooms', sa.Column('floor_width', sa.Integer(), nullable=False, server_default='20'))
    op.add_column('rooms', sa.Column('floor_height', sa.Integer(), nullable=False, server_default='15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'floor_height')
    op.drop_column('rooms', 'floor_width')
    op.drop_column('racks', 'depth_units')
    op.drop_column('racks', 'width_units')
    op.drop_column('racks', 'pos_y')
    op.drop_column('racks', 'pos_x')
    # ### end Alembic commands ###
